name: gestao_financeira
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_modular: ^5.0.3
  flutter_mobx: ^2.2.1
  mobx: ^2.3.3+2
  responsive_builder: ^0.7.1
  flutter_smart_dialog: ^4.9.8+1
  flutter_dotenv: ^5.1.0

  flutter_localizations:
    sdk: flutter
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  animated_snack_bar: ^0.4.0
  flutter_icon_snackbar: ^1.1.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.6.1
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/img/